name: 2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
#   push:
#     branches: [main]
  schedule:
    - cron: '46 8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: 2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror:
    env:
      PAT: ${{ secrets.PAT }}
      DEFAULT_DST: github/back8
      DEFAULT_RENAME_FMT: 's/(.*)/${SRC_TYPE}_${SRC_ACCOUNT}_\1/g'
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event.sender.login == 'fakegit'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: | 
            "${{ github.workspace }}/.cache"
          key: ${{ runner.os }}-cache-actions

      - name: mirror github/cteamx
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/cteamx
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "Thief,Thief-Book-VSCode,BiMo,Wenku"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/streamlit
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/streamlit
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "streamlit"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/nonebot
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/nonebot
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "nb-cli,nonebot2,nonetrip,nonebot,plugin-test,aiocqhttp,vuepress-theme-nonebot,plugin-apscheduler,nonebot-anime,nonebot-alarm,nonebot-tuling"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/python-visualization
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/python-visualization
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "folium"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
          
      - name: mirror github/guofei9987
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/guofei9987
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "blind_watermark"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/CoiaPrant
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/CoiaPrant
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "MediaUnlock_Test"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/sjlleo
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/sjlleo
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "netflix-verify"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/sl1673495
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/sl1673495
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "vue-netease-music"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/smalls0098
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/smalls0098
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "video-tools,origin-php-watermark-api"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/WyattBlue
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/WyattBlue
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "auto-editor"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}


      - name: mirror github/Mz49
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Mz49
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "folderclone"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Th3-822
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Th3-822
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "rapidleech"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/history2
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/history2
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "heroku-ttyd"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/snow922841
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/snow922841
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "telegram_channel_downloader"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/expectocode
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/expectocode
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "telegram-export"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Nukesor
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Nukesor
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "archivebot,sticker-finder,hetznerbot"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/uniborg
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/uniborg
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "uniborg"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Boris-code
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Boris-code
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "feapder,feapder_project,news-spider,jmpy"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/fotile96
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/fotile96
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "WVClient3"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/yt-dlp
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/yt-dlp
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "yt-dlp"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/breezedeus
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/breezedeus
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "cnocr,cnstd,cnocr-models"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/coollabsio
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/coollabsio
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "coolify"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/hasse69
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/hasse69
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "rar2fs"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/nickfox-taterli
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/nickfox-taterli
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "goseeder,imghost"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/devourbots
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/devourbots
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "tg_faka_bot"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
