name: 2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
#   push:
#     branches: [main]
  schedule:
    - cron: '46 8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: 2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror:
    env:
      PAT: ${{ secrets.PAT }}
      DEFAULT_DST: github/back8
      DEFAULT_RENAME_FMT: 's/(.*)/${SRC_TYPE}_${SRC_ACCOUNT}_\1/g'
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event.sender.login == 'fakegit'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: | 
            "${{ github.workspace }}/.cache"
          key: ${{ runner.os }}-cache-actions

      - name: mirror github/cteamx
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/cteamx
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "Thief,Thief-Book-VSCode,BiMo,Wenku"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
          
      - name: mirror github/guofei9987
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/guofei9987
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "blind_watermark"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/CoiaPrant
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/CoiaPrant
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "MediaUnlock_Test"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/sjlleo
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/sjlleo
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "netflix-verify"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/sl1673495
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/sl1673495
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "vue-netease-music"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/smalls0098
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/smalls0098
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "video-tools,origin-php-watermark-api"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
