name: clash

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
#   push:
#     branches: [main]
  schedule:
    - cron: '50 3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: clash

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror:
    env:
      PAT: ${{ secrets.PAT }}
      DEFAULT_DST: github/back8
      DEFAULT_RENAME_FMT: 's/(.*)/${SRC_TYPE}_${SRC_ACCOUNT}_\1/g'
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event.sender.login == 'fakegit'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: | 
            "${{ github.workspace }}/.cache"
          key: ${{ runner.os }}-cache-actions

      - name: mirror github/eycorsican
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/eycorsican
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "go-tun2socks,leaf"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/v2ray
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/v2ray
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "v2ray-core,V2RayN"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/v2fly
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/v2fly
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "geoip,v2ray-core"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/lzdnico
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/lzdnico
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "ClashWeb,subconverteriniexample"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Dreamacro
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Dreamacro
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "clash,clash-dashboard,clash-ctl,Razord"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/yichengchen
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/yichengchen
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "clashX"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/SpongeNobody
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/SpongeNobody
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "Clashy"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/DivineEngine
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/DivineEngine
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "Profiles"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/StevenBlack
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/StevenBlack
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "hosts"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/CareyWang
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/CareyWang
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "sub-web"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/leosam2048
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/leosam2048
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "sub-web"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/tindy2013
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/tindy2013
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "subconverter,stairspeedtest-reborn,stairspeedtest,clashcmd"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/v2board
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/v2board
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "v2board,v2board-admin,v2board-docs,v2board-user,v2board-user-i18n,v2board-docker"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/ACL4SSR
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/ACL4SSR
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "ACL4SSR"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/NyanChanMeow
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/NyanChanMeow
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "SSRSpeed"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Alex950808
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Alex950808
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "proxypool038,v2ray-subscribed"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/badafans
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/badafans
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "better-cloudflare-ip"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/QIN2DIM
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/QIN2DIM
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "V2RayCloudSpider"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Anankke
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Anankke
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "SSPanel-Uim,shadowsocks-mod"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/ilpl
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/ilpl
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "proxypool"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Jrohy
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Jrohy
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "multi-v2ray,docker-install,k8s-install,trojan,python3-install,webssh,trojan-web,nodejs-install,go-install,sshcopy,mysqldump,"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/sjqzhang
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/sjqzhang
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "go-fastdfs,ops_channel"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/pojiezhiyuanjun
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/pojiezhiyuanjun
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "freev2"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/freefq
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/freefq
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "free"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/ruanfei
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/ruanfei
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "ShadowsocksRRShare"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/selierlin
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/selierlin
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "Share-SSR-V2ray"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/pcysanji
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/pcysanji
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "Clash-Web-Bat"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/KOP-XIAO
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/KOP-XIAO
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "QuantumultX-Surge-API,QuantumultX"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/sansui233
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/sansui233
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "proxypool,proxypoolCheck"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/haishanh
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/haishanh
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "yacd"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/JungegeCN
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/JungegeCN
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "JGG,YJL"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Jacobax
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Jacobax
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "proxypool_source,winXray_v3.5.1"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Limerance6
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Limerance6
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "luffy-sama"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/JieErJingFu
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/JieErJingFu
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "FreeNodesTrojanVmessSSRSS"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/adiwzx
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/adiwzx
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "freenode"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/Loyalsoldier
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/Loyalsoldier
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "v2ray-rules-dat,clash-rules,surge-rules,cn-blocked-domain"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror gitee/pm936
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: gitee/pm936
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "httpcatcher"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/ViRb3
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/ViRb3
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "wgcf"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/curve25519xsalsa20poly1305
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/curve25519xsalsa20poly1305
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "docker-wireguard,docker-shadowsocks,docker-tor,docker-aria2,docker-openvpn,docker-wireguard-socks5,docker-wireguard-aria2"
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}

      - name: mirror github/NetchX
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: github/NetchX
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "Netch,NetchBinaries"
          src_account_type: org
          dst_account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
