name: mirror-regex

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: mirror-regex

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror:
    env:
      PAT: ${{ secrets.PAT }}
      DEFAULT_DST: github/back8
      DEFAULT_RENAME_FMT: 's/(.*)/${SRC_TYPE}_${SRC_ACCOUNT}.\1/g'
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event.sender.login == 'fakegit'

    steps:
      - uses: actions/checkout@v2



      - name: mirror github/jiupinjia
        uses: fakedon/hub-mirror@regex
        with:
          src: github/jiupinjia
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "SkyAR"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
