name: mirror

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: mirror

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event.sender.login == 'fakegit'

    steps:
      - uses: actions/checkout@v2

      - name: mirror github/P3TERX
        uses: fakedon/hub-mirror@main
        with:
          src: github/P3TERX
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "debugger-action,ssh2actions,ActionsVM,ca-certificates.crt,GeoLite.mmdb,OpenWrt-Newifi_D2,Actions-OpenWrt,Docker-Aria2-Pro,IBM-CF-V2,aria2.conf"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

      - name: mirror github/horryruo
        uses: fakedon/hub-mirror@main
        with:
          src: github/horryruo
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "multi-bot,ikoa-vps"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

      - name: mirror github/mason1901
        uses: fakedon/hub-mirror@main
        with:
          src: github/mason1901
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "ikoa-web"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

      - name: mirror github/135e2
        uses: fakedon/hub-mirror@main
        with:
          src: github/135e2
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "proxypool"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

      - name: mirror github/wei
        uses: fakedon/hub-mirror@main
        with:
          src: github/wei
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "ssr-scraper,pull,git-sync,minifier"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

      - name: mirror github/repo-sync
        uses: fakedon/hub-mirror@main
        with:
          src: github/repo-sync
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "pull-request,github-sync,repo-sync"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

      - name: mirror github/deepfakes
        uses: fakedon/hub-mirror@main
        with:
          src: github/deepfakes
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "faceswap"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

      - name: mirror github/instantbox
        uses: fakedon/hub-mirror@main
        with:
          src: github/instantbox
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "instantbox"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

      - name: mirror github/listen-now
        uses: fakedon/hub-mirror@main
        with:
          src: github/listen-now
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "listen-now,listen-now-react,listen-now-desktop"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

      - name: mirror github/mozilla
        uses: fakedon/hub-mirror@main
        with:
          src: github/mozilla
          dst: github/back8
          dst_key: ${{ secrets.FAKEGIT_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.FAKEGIT_GITHUB_TOKEN }}
          static_list: "send,DeepSpeech"
          # white_list: "debugger-action"
          account_type: org
          rename_dst: true

